#!/bin/bash

c="${1:- 0}"

{
	urls=()
	while read url title <&3 ; do
		urls+=("$url")
		titles+=("$title")
	done

	unset TMOUT
	pause=20
	for ((; c < ${#urls[@]}; c++)) ; do
		i="${urls[c]}"
		((c%5 == 0)) && {
			while read -sn 1 -t $pause key ; do
				case $key in
					[sp])
						read -sn1 -p $'Paused\n'
						;;
					'+')
						((pause=pause+5))
						echo "Delay: $pause"
						;;
					'-')
						((pause > 5)) && ((pause=pause-5))
						echo "Delay: $pause"
						;;
					*)
						break;
				esac
			done
		}
		echo "$((c+1)) ${titles[c]}"
		firefox -new-tab "$i"
	done
} 3< <( 
	q=".separator ' |'\n"
	q+="SELECT i.url,f.title,i.title FROM rss_item AS i JOIN rss_feed AS f ON i.feedurl = f.rssurl "
	q+="WHERE unread = 1 AND deleted = 0 AND feedurl = '%s' ORDER BY   pubDate ASC;"
	grep '^http.*tumblr' /mnt/sda1/tumblr.urls | sed 's/ .*//' | \
	while read feed ; do
		printf "$q" "$feed" | sqlite3 /mnt/sda1/tumblr.cache.db
	done
)
# vim:sw=4:ts=4
