#!/bin/bash

date
echo "Wake me up in ${1}m"
[[ $1 ]] && sleep "${1}m"
sudo /usr/bin/amixer set Headphone 0

wav='~/bin/alarm_clock_1.wav'
for i in 10 20 30 40 50 60 ; do 
	sudo /usr/bin/amixer set Headphone $i
	mplayer "$wav"
	sleep 120
done
